### ISSUE TITLE
Peer to Peer Code review

### ISSUE THREAD

**Issue by ndayishimiyeeric** [Ogaga01/Ogagas-portfolio#6]
### Hello Ogaga the clean is clean 💯  but there is something you need to improve.

- Please avoid using semantic tags inside each other. for example it is not good practice to use `section` inside another `section`.
- Please try to use em and rem units. This practice will improve the responsivness of your designs.

### Happy Coding 🤙

**Comment by Ogaga01** [comment]
I would work on that
